# Generated by Django 3.2.4 on 2021-09-30 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('student_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_branch', models.CharField(choices=[('CSE', 'CSE'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('ECE', 'ECE'), ('MECH', 'MECH')], max_length=10)),
                ('purpose', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('exit_time', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 16, 24, 2, 640609))),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='records',
        ),
    ]
